### ISSUE TITLE
Fix CancellationException on application stop

### ISSUE THREAD

**Issue by shishkovilja** [shishkovilja/ignitop#26]
Below exception can occur on application stop (usually by `Ctrl + C`):
```
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.CancellationException
	at dev.ignitop.IgniTop.main(IgniTop.java:44)
Caused by: java.util.concurrent.CancellationException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:121)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at dev.ignitop.IgniTop.main(IgniTop.java:41)
```

It should be ignored or handled.

**Comment by shishkovilja** [comment]
Fixed in https://github.com/shishkovilja/ignitop/commit/003e803733dba7fe955bda6060ae959fdce70416
