### ISSUE TITLE
Properly handle re-connection to client nodes

### ISSUE THREAD

**Issue by shishkovilja** [shishkovilja/ignitop#36]
Currently, after a shutdown of all server nodes topology information can not be requested, and a following errors occurs:

```
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.apache.ignite.client.ClientException: org.apache.ignite.client.ClientException: Ignite failed to process request [4]: Failed to execute task, client node disconnected. (server status code [1])
	at dev.ignitop.IgniTop.main(IgniTop.java:58)
Caused by: java.util.concurrent.ExecutionException: org.apache.ignite.client.ClientException: org.apache.ignite.client.ClientException: Ignite failed to process request [4]: Failed to execute task, client node disconnected. (server status code [1])
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at dev.ignitop.IgniTop.main(IgniTop.java:55)
Caused by: org.apache.ignite.client.ClientException: org.apache.ignite.client.ClientException: Ignite failed to process request [4]: Failed to execute task, client node disconnected. (server status code [1])
	at org.apache.ignite.internal.client.thin.ClientComputeImpl.handleExecuteInitFuture(ClientComputeImpl.java:235)
	at org.apache.ignite.internal.client.thin.ClientComputeImpl.lambda$executeAsync0$2(ClientComputeImpl.java:201)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.apache.ignite.internal.client.thin.ReliableChannel.lambda$handleServiceAsync$4(ReliableChannel.java:273)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at org.apache.ignite.internal.client.thin.TcpClientChannel.lambda$null$1(TcpClientChannel.java:364)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: org.apache.ignite.client.ClientException: Ignite failed to process request [4]: Failed to execute task, client node disconnected. (server status code [1])
	at org.apache.ignite.internal.client.thin.TcpClientChannel.convertException(TcpClientChannel.java:378)
	... 7 more
Caused by: org.apache.ignite.internal.client.thin.ClientServerError: Ignite failed to process request [4]: Failed to execute task, client node disconnected. (server status code [1])
	at org.apache.ignite.internal.client.thin.TcpClientChannel.processNextMessage(TcpClientChannel.java:468)
	at org.apache.ignite.internal.client.thin.TcpClientChannel.onMessage(TcpClientChannel.java:204)
	at org.apache.ignite.internal.client.thin.io.gridnioserver.GridNioClientConnection.onMessage(GridNioClientConnection.java:86)
	at org.apache.ignite.internal.client.thin.io.gridnioserver.GridNioClientListener.onMessage(GridNioClientListener.java:56)
	at org.apache.ignite.internal.client.thin.io.gridnioserver.GridNioClientListener.onMessage(GridNioClientListener.java:30)
	at org.apache.ignite.internal.util.nio.GridNioFilterChain$TailFilter.onMessageReceived(GridNioFilterChain.java:279)
	at org.apache.ignite.internal.util.nio.GridNioFilterAdapter.proceedMessageReceived(GridNioFilterAdapter.java:109)
	at org.apache.ignite.internal.util.nio.GridNioCodecFilter.onMessageReceived(GridNioCodecFilter.java:116)
	at org.apache.ignite.internal.util.nio.GridNioFilterAdapter.proceedMessageReceived(GridNioFilterAdapter.java:109)
	at org.apache.ignite.internal.util.nio.GridNioServer$HeadFilter.onMessageReceived(GridNioServer.java:3752)
	at org.apache.ignite.internal.util.nio.GridNioFilterChain.onMessageReceived(GridNioFilterChain.java:175)
	at org.apache.ignite.internal.util.nio.GridNioServer$ByteBufferNioClientWorker.processRead(GridNioServer.java:1211)
	at org.apache.ignite.internal.util.nio.GridNioServer$AbstractNioClientWorker.processSelectedKeysOptimized(GridNioServer.java:2526)
	at org.apache.ignite.internal.util.nio.GridNioServer$AbstractNioClientWorker.bodyInternal(GridNioServer.java:2281)
	at org.apache.ignite.internal.util.nio.GridNioServer$AbstractNioClientWorker.body(GridNioServer.java:1910)
	at org.apache.ignite.internal.util.worker.GridWorker.run(GridWorker.java:125)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

It should be properly handled, by a one of the following ways:
1. Allow to work on such cluster.
2. Throw error with more suitable message.

**Comment by shishkovilja** [comment]
It seems, that task calls on disconnected client are unsupported by Ignite.
