### ISSUE TITLE
Fix failure, when terminal width less than summary headers width

### ISSUE THREAD

**Issue by shishkovilja** [shishkovilja/ignitop#40]
```
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.UnknownFormatConversionException: Conversion = '-'
	at dev.ignitop.IgniTop.main(IgniTop.java:58)
Caused by: java.util.concurrent.ExecutionException: java.util.UnknownFormatConversionException: Conversion = '-'
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at dev.ignitop.IgniTop.main(IgniTop.java:55)
Caused by: java.util.UnknownFormatConversionException: Conversion = '-'
	at java.base/java.util.Formatter.checkText(Formatter.java:2732)
	at java.base/java.util.Formatter.parse(Formatter.java:2718)
	at java.base/java.util.Formatter.format(Formatter.java:2655)
	at java.base/java.io.PrintStream.format(PrintStream.java:1053)
	at java.base/java.io.PrintStream.printf(PrintStream.java:949)
	at dev.ignitop.ui.component.impl.Table.printHeader(Table.java:139)
	at dev.ignitop.ui.component.impl.Table.render(Table.java:111)
	at dev.ignitop.ui.TerminalUi.refresh(TerminalUi.java:49)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by shishkovilja** [comment]
Fixed in #6
